// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3352.RobotCode2016;

import edu.wpi.first.wpilibj.IterativeRobot;
import edu.wpi.first.wpilibj.PowerDistributionPanel;
import edu.wpi.first.wpilibj.Servo;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.Scheduler;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import org.usfirst.frc3352.RobotCode2016.commands.*;
import org.usfirst.frc3352.RobotCode2016.commands.DriveAcrossDefense_Auto.Defense;
import org.usfirst.frc3352.RobotCode2016.subsystems.*;

import com.ni.vision.NIVision;
import com.ni.vision.NIVision.FlipAxis;
import com.ni.vision.NIVision.Image;

import edu.wpi.first.wpilibj.CameraServer;
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.vision.AxisCamera;
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.DoubleSolenoid.Value;

/**
 * The VM is configured to automatically run this class, and to call the
 * functions corresponding to each mode, as described in the IterativeRobot
 * documentation. If you change the name of this class or the package after
 * creating this project, you must also update the manifest file in the resource
 * directory.
 */
public class Robot extends IterativeRobot {

    Command driveAcrossDefense;
    Command driveToDefense;
    Command doNothing;
    Command autonomousCommand;
    CameraServer server;
    public static OI oi;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static Drivetrain drivetrain;
    public static Shooter shooter;
    public static Shooter shooter2;
    public static PowerDistributionPanel pdp;
    
    public static ShooterPneumatics shooterpneumatics;
    
    public static GearShifter gearshift;
    public static Compressor comp;
    public static Image frame;
    public static AxisCamera camera;
    public static Servo camAngle;
    static SendableChooser auto;
    

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    /**
     * This function is run when the robot is first started up and should be
     * used for any initialization code.
     */
    public void robotInit() {
    	RobotMap.init();
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        drivetrain = new Drivetrain();
        shooter = new Shooter();
        shooterpneumatics = new ShooterPneumatics();
        pdp = new PowerDistributionPanel();
        
        gearshift = new GearShifter();
        comp = new Compressor();
        comp.start();
        camAngle = new Servo(0);
        

        // open the camera at the IP address assigned. This is the IP address that the camera
        // can be accessed through the web interface.
        auto = new SendableChooser();
        
        
        //TODO implement vision code
//        server = CameraServer.getInstance();
//      	server.setQuality(50);
        //the camera name (ex "cam0") can be found through the roborio web interface
        //server.startAutomaticCapture("cam0");
//        frame = NIVision.imaqCreateImage(NIVision.ImageType.IMAGE_RGB, 0);

        // open the camera at the IP address assigned. This is the IP address that the camera
        // can be accessed through the web interface.
//        camera = new AxisCamera("169.254.13.28");
        

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        // OI must be constructed after subsystems. If the OI creates Commands
        //(which it very likely will), subsystems are not guaranteed to be
        // constructed yet. Thus, their requires() statements may grab null
        // pointers. Bad news. Don't move it.
        oi = new OI();

        // instantiate the command used for the autonomous period
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS

        driveAcrossDefense = new DriveAcrossDefense_Auto(Defense.LOWBAR);
        driveToDefense = new DriveToDefense_Auto();
        doNothing = new DoNothing_Auto();

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS
    }

    /**
     * This function is called when the disabled button is hit.
     * You can use it to reset subsystems before shutting down.
     */
    public void disabledInit(){
    	RobotMap.cameraLED.set(false);
    	auto.addDefault("Do Nothing", doNothing);
    	auto.addObject("Drive Across Defense", driveAcrossDefense);
    	auto.addObject("Drive to Outer Works", driveToDefense);
    	SmartDashboard.putData("Auto modes", auto);
    	gearshift.ShiftDown();
    }

    public void disabledPeriodic() {
        Scheduler.getInstance().run();
 //       camera.getImage(frame);
        SmartDashboard.putString("disabled", auto.getSelected().toString());
 //       NIVision.imaqFlip(frame, frame, FlipAxis.HORIZONTAL_AXIS);
 //       CameraServer.getInstance().setImage(frame);
    }

    public void autonomousInit() {
        // schedule the autonomous command (example)
    	autonomousCommand = (Command) auto.getSelected();
        SmartDashboard.putString("auto", auto.getSelected().toString());
        if (autonomousCommand != null) autonomousCommand.start();
        RobotMap.cameraLED.set(true);
        camAngle.set(.12);
    }

    /**
     * This function is called periodically during autonomous
     */
    public void autonomousPeriodic() {
        Scheduler.getInstance().run();
    }

    public void teleopInit() {
        // This makes sure that the autonomous stops running when
        // teleop starts running. If you want the autonomous to
        // continue until interrupted by another command, remove
        // this line or comment it out.
        if (autonomousCommand != null) autonomousCommand.cancel();
        RobotMap.cameraLED.set(true);
        comp.start();
        camAngle.set(.12);
    }

    /**
     * This function is called periodically during operator control
     */
    public void teleopPeriodic() {
        Scheduler.getInstance().run();
        SmartDashboard.putNumber("angle", Robot.shooter.getAngle());
        SmartDashboard.putBoolean("shift state", (Robot.gearshift.ShiftState()==Value.kReverse));
/*        
        camera.getImage(frame);
        NIVision.imaqFlip(frame, frame, FlipAxis.HORIZONTAL_AXIS);
//        NIVision.imaqDrawShapeOnImage(frame, frame, rect, DrawMode.DRAW_VALUE, ShapeMode.SHAPE_OVAL, 0.0f);

        CameraServer.getInstance().setImage(frame);
*/
    }

    public void testInit() {
    	RobotMap.cameraLED.set(true);
    }
    /**
     * This function is called periodically during test mode
     */
    public void testPeriodic() {
        LiveWindow.run();
    }
}
