// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc3352.RobotCode2016;

import edu.wpi.first.wpilibj.IterativeRobot;
import edu.wpi.first.wpilibj.PowerDistributionPanel;
import edu.wpi.first.wpilibj.command.Command;
import edu.wpi.first.wpilibj.command.Scheduler;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import org.usfirst.frc3352.RobotCode2016.commands.*;
import org.usfirst.frc3352.RobotCode2016.commands.DriveAcrossDefense_Auto.Defense;
import org.usfirst.frc3352.RobotCode2016.subsystems.*;

import com.ni.vision.NIVision;
import com.ni.vision.NIVision.Image;

import edu.wpi.first.wpilibj.CameraServer;
import edu.wpi.first.wpilibj.smartdashboard.SendableChooser;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;
import edu.wpi.first.wpilibj.Compressor;
import edu.wpi.first.wpilibj.DoubleSolenoid.Value;

/**
 * The VM is configured to automatically run this class, and to call the
 * functions corresponding to each mode, as described in the IterativeRobot
 * documentation. If you change the name of this class or the package after
 * creating this project, you must also update the manifest file in the resource
 * directory.
 */
public class Robot extends IterativeRobot {

    Command driveAcrossDefense;
    Command driveToDefense;
    Command doNothing;
    Command autonomousCommand;
    CameraServer server;
    public static OI oi;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static Drivetrain drivetrain;
    public static Shooter shooter;
    public static Shooter shooter2;
    public static PowerDistributionPanel pdp;
    
    public static ShooterPneumatics shooterpneumatics;
    
    public static GearShifter gearshift;
    public static Compressor comp;
    public static CameraServer camera;
    public static Image frame;
    public static Image binaryFrame;
    NIVision.Range hue = new NIVision.Range(17, 85);
    NIVision.Range saturation = new NIVision.Range(137, 255);
    NIVision.Range luminance = new NIVision.Range(77, 194);
    int session;
    final NIVision.Rect rect = new NIVision.Rect(10, 0, 100, 100);
    
    private static final int kSize640x480 = 0;
    private static final int kSize320x240 = 1;
    private static final int kSize160x120 = 2;

    static SendableChooser autoChooser;
    static SendableChooser defenseChooser;
    static Defense defense = Defense.ROCKWALL;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    /**
     * This function is run when the robot is first started up and should be
     * used for any initialization code.
     */
    public void robotInit() {
    	RobotMap.init();
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        drivetrain = new Drivetrain();
        shooter = new Shooter();
        shooterpneumatics = new ShooterPneumatics();
        pdp = new PowerDistributionPanel();
        
        gearshift = new GearShifter();
        comp = new Compressor();
        comp.start();
        
        autoChooser = new SendableChooser();
        defenseChooser = new SendableChooser();
        
        //CameraServer.getInstance().setSize(kSize640x480);
        
        frame = NIVision.imaqCreateImage(NIVision.ImageType.IMAGE_RGB, 0);
        binaryFrame = NIVision.imaqCreateImage(NIVision.ImageType.IMAGE_U8, 0);

        // the camera name (ex "cam0") can be found through the roborio web interface
        //session = NIVision.IMAQdxOpenCamera("cam0", NIVision.IMAQdxCameraControlMode.CameraControlModeController);
        //NIVision.IMAQdxConfigureGrab(session);
        

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        // OI must be constructed after subsystems. If the OI creates Commands
        //(which it very likely will), subsystems are not guaranteed to be
        // constructed yet. Thus, their requires() statements may grab null
        // pointers. Bad news. Don't move it.
        oi = new OI();

        // instantiate the command used for the autonomous period
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS
        
        driveAcrossDefense = new DriveAcrossDefense_Auto(defense);
        driveToDefense = new DriveToDefense_Auto();
        doNothing = new DoNothing_Auto();

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=AUTONOMOUS
    }

    /**
     * This function is called when the disabled button is hit.
     * You can use it to reset subsystems before shutting down.
     */
    public void disabledInit(){
    	RobotMap.cameraLED.set(false);
    	
    	autoChooser.addDefault("Do Nothing", doNothing);
    	autoChooser.addObject("Drive Across Defense", driveAcrossDefense);
    	autoChooser.addObject("Drive to Outer Works", driveToDefense);
    	SmartDashboard.putData("Auto modes", autoChooser);
    	
    	defenseChooser.addDefault("Rock Wall", Defense.ROCKWALL);
    	defenseChooser.addObject("Rough Terrain", Defense.ROUGH);
    	defenseChooser.addObject("Low Bar", Defense.LOWBAR);
    	defenseChooser.addObject("Ramparts", Defense.RAMPART);
    	defenseChooser.addObject("Moat", Defense.MOAT);
    	defenseChooser.addObject("Cheval de Frise", Defense.CHEVAL);
    	SmartDashboard.putData("Autonomous Defense", defenseChooser);
    	
    	gearshift.ShiftDown();
    }

    public void disabledPeriodic() {
        Scheduler.getInstance().run();
        
        SmartDashboard.putString("Auto Selector", autoChooser.getSelected().toString());
        SmartDashboard.putString("Defense Selector", defenseChooser.getSelected().toString());
        
        //NIVision.IMAQdxGrab(session, frame, 1);
        //NIVision.imaqColorThreshold(binaryFrame, frame, 255, NIVision.ColorMode.HSL, hue, saturation, luminance);
        
        //CameraServer.getInstance().setImage(frame);
        
        // This code will update the location of the rectangle each time through
        // the loop to simulate a vision algorithm that is moving the overlay on the image
        //rect.left = (rect.left + 5) % 200;
    }

    public void autonomousInit() {
        // schedule the autonomous command (example)
    	autonomousCommand = (Command) autoChooser.getSelected();
    	defense = (Defense) defenseChooser.getSelected();
    	if(autonomousCommand == driveAcrossDefense){
    		if(defense == Defense.CHEVAL || defense == Defense.PORTCULLIS || defense == Defense.DRAWBRIDGE || defense == Defense.SALLY){
    			autonomousCommand = driveToDefense;
    		}else{
    			driveAcrossDefense = new DriveAcrossDefense_Auto(defense);
    		}
    	}
        SmartDashboard.putString("Auto", autoChooser.getSelected().toString());
        SmartDashboard.putString("Defense", defenseChooser.getSelected().toString());
        if (autonomousCommand != null) autonomousCommand.start();
        RobotMap.cameraLED.set(true);
    }

    /**
     * This function is called periodically during autonomous
     */
    public void autonomousPeriodic() {
        Scheduler.getInstance().run();
    }

    public void teleopInit() {
        // This makes sure that the autonomous stops running when
        // teleop starts running. If you want the autonomous to
        // continue until interrupted by another command, remove
        // this line or comment it out.
        if (autonomousCommand != null) autonomousCommand.cancel();
        RobotMap.cameraLED.set(true);
        comp.start();
    }

    /**
     * This function is called periodically during operator control
     */
    public void teleopPeriodic() {
        Scheduler.getInstance().run();
        SmartDashboard.putNumber("angle", Robot.shooter.getAngle());
        SmartDashboard.putBoolean("shift state", (Robot.gearshift.ShiftState()==Value.kReverse));
    }

    public void testInit() {
    	RobotMap.cameraLED.set(true);
    }
    /**
     * This function is called periodically during test mode
     */
    public void testPeriodic() {
        LiveWindow.run();
    }
}
